### ISSUE TITLE
Support TLSA Record

### ISSUE THREAD

**Issue by felixoi** [octodns/octodns-cloudflare#30]
Source of support (type also available in dashboard): https://blog.cloudflare.com/additional-record-types-available-with-cloudflare-dns/. Mostly used for DANE support in mail servers.

args:
- usage
- selector
- matching_type

Currently my workflow fails because of
```
AttributeError: 'CloudflareProvider' object has no attribute '_data_for_TLSA'. Did you mean: '_data_for_A'?
```
There is nothing configured in octodns for TLSA just a manual dns record using the dashboard.

**Comment by ross** [comment]
> ```
> AttributeError: 'CloudflareProvider' object has no attribute '_data_for_TLSA'. Did you mean: '_data_for_A'?
> ```

How'd you hit that error? I just created a `TLSA` record in my test setup and it's skipped/ignored as expected/:

I can only get that to happen when `TLSA` is added to the `SUPPORTS` list on the provider. Support for the type can be added, but obviously isn't included currently.

**Comment by felixoi** [comment]
@ross As I didn't edit the list, I've checked some other things and it seems like the error started because of an unescaped IPv6 address (introduced in https://github.com/felixoi/dns/blob/c8e1eb5c0159f305483ab5b60a7cf10f6761934d/shared/mail-new.yaml). After wrapping it in `"` it now works again. Still I don't expect the TLSA error when having something unescaped. 
Thanks for the support PR, as this enabled me to manage the TLSA record using octodns.

**Comment by ross** [comment]
> It happend randomly again after it worked before when escaping an IPv6 address ([felixoi/dns@e55dabd](https://github.com/felixoi/dns/commit/e55dabd78deb4e024f553ce73b7f54c98899c240)).

Hrm, I'll have to take another look at the provider. I didn't see a way for it to get to the point of trying to call that method, but regardless the PR should address it.

**Comment by ross** [comment]
Fixed by https://github.com/octodns/octodns-cloudflare/pull/31
