### ISSUE TITLE
Add extra details for documentations: Required permissions for token creation

### ISSUE THREAD

**Issue by chez14** [octodns/octodns-cloudflare#49]
I think we can improve the documentation by adding extra details of required permission because Cloudflare have detailed settings for each feature.

I'm thinking this (please correct me if I'm wrong):
- To dump:
  - Zone:Read 
- To edit:
  - DNS:Edit
  - DNS:Read

This issue coming from my first time testing this provider, and a little bit confused on what permission should I allow this token do. At first I thought DNS:Edit and DNS:Read is sufficient, but turn out we need Zone:Read instead of DNS:Read.

Let me know what do you think. If it's okay, I'll send an MR with proposed improved documentation.

Thank you!

**Comment by yzguy** [comment]
This is definitely a good addition IMO, I was doing something in Terraform the other day and I wanted to make a limited token and it was a bit of a struggle to know what permissions were needed.

**Comment by chez14** [comment]
Hi @yzguy,

I've made a PR for this issue, can you please review it? The PR can be checked on #50.

Please let me know if you have any feedback or questions.

Thank you!
