### ISSUE TITLE
Need to enable PageRule Edit scope in API Token for use with URLFWD

### ISSUE THREAD

**Issue by diamondzxd** [octodns/octodns-cloudflare#83]
If the user wants to use the URLFWD, then PageRule Edit scope should be enabled while creating the API Token in Cloudflare, otherwise the following Exception will be thrown : 

```python
octodns_cloudflare.CloudflareAuthenticationError: Unauthorized to access requested resource
```
Can we add this note in the documentation?

**Comment by ross** [comment]
> Can we add this note in the documentation?

Definitely. PRs welcome.
